/// Flutter icons MyCustomIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcon
///      fonts:
///       - asset: fonts/MyCustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomIcon {
  MyCustomIcon._();

  static const _kFontFam = 'MyCustomIcon';
  static const String? _kFontPkg = null;

  static const IconData order = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkout = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
